import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import Chat from "@/components/layouts/Chat";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { ThemeScript } from "@/components/providers/ThemeScript";
import { LanguageProvider } from "@/components/providers/LanguageProvider";
import { LanguageScript } from "@/components/providers/LanguageScript";
import { Language } from "@/data/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read language from cookie on the server
  const cookieStore = await cookies();
  const languageCookie = cookieStore.get('language')?.value;
  const initialLanguage: Language = (languageCookie === 'en' || languageCookie === 'am') 
    ? languageCookie 
    : 'en';

  return (
    <html lang={initialLanguage} suppressHydrationWarning>
      <body className="antialiased">
        <LanguageScript initialLanguage={initialLanguage} />
        <ThemeScript />
        <ThemeProvider>
          <LanguageProvider initialLanguage={initialLanguage}>
            <Header />
            {children}
            <Footer />
            <Chat />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
